#!/usr/bin/env python3
"""
Export ONNX files for a selected split configuration.

Reads artifacts/split_configs/<model>/<name>.json (generated by script 30)
and exports merged-chunk ONNX graphs plus the full-model ONNX.

Usage
-----
conda run -n trt python scripts/31_export_selected_split.py \
  --model alexnet --name alexnet_max22

conda run -n trt python scripts/31_export_selected_split.py \
  --model vgg19 --name vgg19_poolstage --skip-full
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

from src.export.onnx_exporter import export_module
from src.models.registry import build_model, get_model_info
from src.splitting.dag_aligned_split import make_dag_aligned_chunks
from src.splitting.selective_split import build_merged_module


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Export ONNX files for a selected split configuration."
    )
    parser.add_argument("--model", required=True, help="Model name, e.g. alexnet")
    parser.add_argument("--name", required=True, help="Selected variant name")
    parser.add_argument(
        "--base-variant", default="dag_aligned_full",
        help="Base variant (default: dag_aligned_full)",
    )
    parser.add_argument("--skip-full", action="store_true", help="Skip full-model ONNX")
    parser.add_argument("--device", default="cuda")
    args = parser.parse_args()

    cfg_path = REPO / "artifacts" / "split_configs" / args.model / f"{args.name}.json"
    if not cfg_path.exists():
        print(f"Config not found: {cfg_path.relative_to(REPO)}")
        print("Run script 30 first.")
        sys.exit(1)

    cfg = json.loads(cfg_path.read_text())
    n_chunks = cfg["n_chunks"]
    n_base = cfg["candidate_count"]
    print(f"\n{'=' * 60}")
    print(f"Exporting: {args.model} / {args.name}")
    print(f"  Base chunks : {n_base}  →  Selected chunks: {n_chunks}")
    print(f"{'=' * 60}")

    # Load base model + base chunk modules once
    info = get_model_info(args.model)
    model = build_model(args.model)
    base_specs = make_dag_aligned_chunks(args.model, model)

    # Full model ONNX
    full_onnx = REPO / cfg["full_model"]["onnx"]
    if not args.skip_full:
        print(f"\n  [full model]  input={info.input_shape}")
        export_module(build_model(args.model), info.input_shape, full_onnx, device=args.device)
    else:
        print("\n  [full model]  skipped (--skip-full)")

    # Chunk ONNXes
    print("\n  [chunks]")
    groups = cfg["merged_groups"]
    for grp_id, grp_chunk_ids in enumerate(groups):
        chunk_cfg = cfg["chunks"][grp_id]
        onnx_path = REPO / chunk_cfg["onnx"]
        in_shape = tuple(chunk_cfg["input_shape"])
        out_shape = tuple(chunk_cfg["output_shape"])
        desc = chunk_cfg["description"]

        base_modules = [base_specs[i].module for i in grp_chunk_ids]
        merged_mod, _ = build_merged_module(base_modules, in_shape)

        print(f"  chunk{grp_id}  ({len(grp_chunk_ids)} base chunks merged)  "
              f"{in_shape} → {out_shape}")
        print(f"    [{desc}]")
        export_module(merged_mod, in_shape, onnx_path, device=args.device)

    print(f"\nAll exports done for {args.name}.")
    print(f"Next: bash scripts/32_build_selected_engines.sh --model {args.model} --name {args.name}")


if __name__ == "__main__":
    main()
